// <auto-generated />
using System;
using Entekhab_Vahed_Wpf.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entekhab_Vahed_Wpf.Migrations
{
    [DbContext(typeof(EVContext))]
    [Migration("20200615130046_admintable")]
    partial class admintable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.ChooseUnit", b =>
                {
                    b.Property<int>("CUCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<int?>("LessonlCode")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorpCode")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsCode")
                        .HasColumnType("int");

                    b.Property<int>("cUnit")
                        .HasColumnType("int");

                    b.Property<int>("field_id")
                        .HasColumnType("int");

                    b.Property<int>("lesson_code")
                        .HasColumnType("int");

                    b.Property<int>("prof_id")
                        .HasColumnType("int");

                    b.Property<int>("stud_id")
                        .HasColumnType("int");

                    b.HasKey("CUCode");

                    b.HasIndex("FieldId");

                    b.HasIndex("LessonlCode");

                    b.HasIndex("ProfessorpCode");

                    b.HasIndex("StudentsCode");

                    b.ToTable("ChooseUnit");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Classx", b =>
                {
                    b.Property<int>("classCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dates")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LessonlCode")
                        .HasColumnType("int");

                    b.Property<string>("Makan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessorpCode")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Times")
                        .HasColumnType("time");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<int>("lesson_code")
                        .HasColumnType("int");

                    b.Property<int>("prof_id")
                        .HasColumnType("int");

                    b.HasKey("classCode");

                    b.HasIndex("LessonlCode");

                    b.HasIndex("ProfessorpCode");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Fieldx", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Lessonx", b =>
                {
                    b.Property<int>("lCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessorpCode")
                        .HasColumnType("int");

                    b.Property<int>("Vahed")
                        .HasColumnType("int");

                    b.Property<int>("field_id")
                        .HasColumnType("int");

                    b.Property<int>("prof_id")
                        .HasColumnType("int");

                    b.HasKey("lCode");

                    b.HasIndex("FieldId");

                    b.HasIndex("ProfessorpCode");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Professorx", b =>
                {
                    b.Property<int>("pCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("field_id")
                        .HasColumnType("int");

                    b.HasKey("pCode");

                    b.HasIndex("FieldId");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Scorex", b =>
                {
                    b.Property<int>("scCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LessonlCode")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorpCode")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsCode")
                        .HasColumnType("int");

                    b.Property<int>("cUnit")
                        .HasColumnType("int");

                    b.Property<int>("lesson_code")
                        .HasColumnType("int");

                    b.Property<int>("prof_id")
                        .HasColumnType("int");

                    b.Property<int>("score1")
                        .HasColumnName("score")
                        .HasColumnType("int");

                    b.Property<int>("stud_id")
                        .HasColumnType("int");

                    b.HasKey("scCode");

                    b.HasIndex("LessonlCode");

                    b.HasIndex("ProfessorpCode");

                    b.HasIndex("StudentsCode");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Studentx", b =>
                {
                    b.Property<int>("sCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NatCode")
                        .HasColumnType("int");

                    b.Property<int>("field_id")
                        .HasColumnType("int");

                    b.HasKey("sCode");

                    b.HasIndex("FieldId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.ChooseUnit", b =>
                {
                    b.HasOne("Entekhab_Vahed_Wpf.Model.Fieldx", "Field")
                        .WithMany("ChooseUnits")
                        .HasForeignKey("FieldId");

                    b.HasOne("Entekhab_Vahed_Wpf.Model.Lessonx", "Lesson")
                        .WithMany("ChooseUnits")
                        .HasForeignKey("LessonlCode");

                    b.HasOne("Entekhab_Vahed_Wpf.Model.Professorx", "Professor")
                        .WithMany("ChooseUnits")
                        .HasForeignKey("ProfessorpCode");

                    b.HasOne("Entekhab_Vahed_Wpf.Model.Studentx", "Student")
                        .WithMany("ChooseUnits")
                        .HasForeignKey("StudentsCode");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Classx", b =>
                {
                    b.HasOne("Entekhab_Vahed_Wpf.Model.Lessonx", "Lesson")
                        .WithMany("Classes")
                        .HasForeignKey("LessonlCode");

                    b.HasOne("Entekhab_Vahed_Wpf.Model.Professorx", "Professor")
                        .WithMany("Classes")
                        .HasForeignKey("ProfessorpCode");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Lessonx", b =>
                {
                    b.HasOne("Entekhab_Vahed_Wpf.Model.Fieldx", "Field")
                        .WithMany("Lessons")
                        .HasForeignKey("FieldId");

                    b.HasOne("Entekhab_Vahed_Wpf.Model.Professorx", "Professor")
                        .WithMany("Lessons")
                        .HasForeignKey("ProfessorpCode");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Professorx", b =>
                {
                    b.HasOne("Entekhab_Vahed_Wpf.Model.Fieldx", "Field")
                        .WithMany("Professors")
                        .HasForeignKey("FieldId");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Scorex", b =>
                {
                    b.HasOne("Entekhab_Vahed_Wpf.Model.Lessonx", "Lesson")
                        .WithMany("Scores")
                        .HasForeignKey("LessonlCode");

                    b.HasOne("Entekhab_Vahed_Wpf.Model.Professorx", "Professor")
                        .WithMany("Scores")
                        .HasForeignKey("ProfessorpCode");

                    b.HasOne("Entekhab_Vahed_Wpf.Model.Studentx", "Student")
                        .WithMany("Scores")
                        .HasForeignKey("StudentsCode");
                });

            modelBuilder.Entity("Entekhab_Vahed_Wpf.Model.Studentx", b =>
                {
                    b.HasOne("Entekhab_Vahed_Wpf.Model.Fieldx", "Field")
                        .WithMany("Students")
                        .HasForeignKey("FieldId");
                });
#pragma warning restore 612, 618
        }
    }
}
